# Generated by Django 3.1.5 on 2021-01-24 01:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='decricao',
            new_name='descricao',
        ),
        migrations.AlterField(
            model_name='contato',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 24, 1, 8, 6, 537786, tzinfo=utc)),
        ),
    ]
